version: "3"


services:
    app:
      image: teslaazad/cmad-cisco:latest
      ports:
        - 8090:8080
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/messages?useSSL=false&allowPublicKeyRetrieval=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
      depends_on:
        - mysql
    frontend:
      image: teslaazad/cmad-cisco-frontend:latest
      ports:
        - 3001:3001
      depends_on:
        - app
    mysql:
      image: mysql
      ports:
        - "3307:3306"
      volumes: ["/var/lib/mysql"]

      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_ROOT_USERNAME=root
        - MYSQL_DATABASE=messages
        - MYSQL_ROOT_HOST=%
